apiVersion: apps/v1 #required fields
kind: DaemonSet #required fields
metadata: #required fields
  name: fluentd-es-demo
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
  matchLabels:
    name: fluentd-es #this must match the label below
  template: #required fields 
    metadata:
      labels:
        name: fluentd-es #this must match the selector above
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  containers:
  - name: fluentd-es-example
    image: k8s.gcr.io/fluentd-elasticsearch:1.20
    resources:
    limits:
      memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: varlog
      mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
        terminationGracePeriodSeconds: 30
    volumes:
    - name: varlog
      hostPath:
        path: /var/log
        - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
