apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
#  persistentVolumeReclaimPolicy: Delete ## Define Reclaim policy as delete, when you delete pvc automatically pv will be deleted if the directory on node created at /tmp/ path. ex: /tmp/kube
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube"  # to be changed as /tmp/kube if reclai policy is Delete
