#PVC Will be same for hostpath volume type and nfs volume type. there will be no change on requesting the persistent volume. only change is in creating and declaring the persistent volume by cluster administrator
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
